CREATE TABLE 'ENTY_SEL_CTA_T' ('ENTY_SEL_CTA_CD' TEXT,'OPT_L
CK' NUMERIC,'ENTY_SEL_CTA_DESC' TEXT,'DIV_CD' TEXT,'STR_ID_Y
N' TEXT,'ENTY_TYP_ENU' NUMERIC,'CTA_SQL' TEXT,'CTA_FIND_ENTY
' TEXT,'CRTD_DTT' TEXT,'CRTD_USR_CD' TEXT,'UPDT_DTT' TEXT,'U
PDT_USR_CD' TEXT,'MAX_ENTYS' NUMERIC);
