CREATE TABLE 'JOB_DEFN_T' ('JOB_CD' TEXT,'OPT_LCK' NUMERIC,'
JOB_DESC' TEXT,'SCHD_TYP_ENU' NUMERIC,'JOB_TYP_ENU' NUMERIC,
'DIV_CD' TEXT,'PARM_1' TEXT,'PARM_2' TEXT,'PARM_3' TEXT,'PAR
M_4' TEXT,'PARM_5' TEXT,'CRTD_DTT' TEXT,'CRTD_USR_CD' TEXT,'
UPDT_DTT' TEXT,'UPDT_USR_CD' TEXT,'TPLT_FILE' TEXT,'OUTPT_FI
LE' TEXT,'SCHD_DETL_ID' NUMERIC,'PRTY' NUMERIC,'ACTV_YN' TEX
T,'NEXT_JOB_CD_SUCCESS' TEXT,'NEXT_JOB_CD_FAILURE' TEXT,'ALR
T_GRP_CD_SUCCESS' TEXT,'ALRT_GRP_CD_FAILURE' TEXT,'GEN_ENTY_
OUTPUT_YN' TEXT,'TPLT_ID' NUMERIC);                          
