CREATE TABLE 'SCHD_DETL_T' ('SCHD_DETL_ID' NUMERIC,'OPT_LCK'
 NUMERIC,'RCURNCE_TYP_ENU' NUMERIC,'EFCT_DT' TEXT,'EXPD_DT' 
TEXT,'STRT_TM' TEXT,'END_TM' TEXT,'DAY_OF_MTH' NUMERIC,'ITVL
' NUMERIC,'FXD_ITVL_SRC_ENU' NUMERIC,'BUS_DAYS_CD' TEXT,'BUS
_MTHS_CD' TEXT);
